### ISSUE TITLE
Error: Internal Server Error

### ISSUE THREAD

**Issue by PleaseInsertNameHere** [rahatarmanahmed/hastebin#8]
Everytime and with every node package I tried, I'm getting an internal server error.
This is my hastebin code:
`const haste = await hastebin.createPaste(loggedContentString, { raw: true, contentType: 'text/plain', server: 'https://hastebin.com'})`

**Comment by rahatarmanahmed** [comment]
Seems like a server issue: https://github.com/seejohnrun/haste-server/issues/370
